### ISSUE TITLE
Multiple login on two devices not possible

### ISSUE THREAD

**Issue by berrywhite96** [Fornoth/spotify-connect-web#105]
I thought I can use several pis to enjoy spotify everywhere in my house. But I tried to start the application on two pis at the same time, and the playback switched from the one to the other one. In my spotify connect list never appears two speakers, either the first or the second.
There are no error lines in the command line.

Thank you for your support!

**Comment by berrywhite96** [comment]
Ok, I found a fix for that. You can't use the same credentials.json more than one time, so just let a new credentials.json generate and use this for the second or third device.

**Comment by mundodisco8** [comment]
can you give more detailed instructions about the Avahi config? I've never used it and I have no clue what to do :S

**Comment by Fornoth** [comment]
@mundodisco8 I updated the readme with some new instructions, can you try those?
