### ISSUE TITLE
Local file problem

### ISSUE THREAD

**Issue by berrywhite96** [Fornoth/spotify-connect-web#107]
Many do not know but spotify allows local files which you can organize on your Mac or PC and then "upload" to ur smartphone or tablet.
This feature isnt handled by spotify connect web, the program exits immediatly. Please add an exception for it, skipping all local files or something like that.

Hopefully I get an answer, otherwise I would like to assume this project, because I am developing something where spotify connect is a big part of.

**Comment by Fornoth** [comment]
Unfortunately I have no control over that part, it's all done in the libspotify_embedded library. You may want to look at https://github.com/plietar/librespot instead, I'm not sure if it has support for local files, but it is open source though, so you could add it if you needed to
