### ISSUE TITLE
Change song

### ISSUE THREAD

**Issue by bnw** [Fornoth/spotify-connect-web#123]
Hi,

I'm trying to create a hardware control for Spotify, e.g. a hardware-button, that starts a certain playlist.
While you already expose a http api for controlling volume, pause, play, skip,... there does not seem to be one to control which song/playlist is played.
If I read the code correctly, https://github.com/plietar/librespot already offers this functionality via `Player::load`.
Would something like this be possible to add?

Thanks a lot
Ben

**Comment by tatoosh** [comment]
+1

**Comment by tml89** [comment]
+1

**Comment by Fornoth** [comment]
This isn't something I can add since the library doesn't expose this functionality, but you can do it via Spotify's Web API https://developer.spotify.com/web-api/start-a-users-playback/
