### ISSUE TITLE
"Radio" playback stops prematurely 

### ISSUE THREAD

**Issue by aloupos** [Fornoth/spotify-connect-web#125]
It seems Spotify changed some things, and now when you are playing radio, the UI shows the first n songs, with a note after that "More songs load as you listen".  The works normally when the device is either local or a native spotify app on another device, however at the last song with the device set to a spotify-connect-web host it doesn't.  

To reproduce, right click a track or artist, and click go to "radio".  Choose the last song in the list (some are grayed but still selectable.  When the list visible song is finished, playback will stop.  The expected behaviour is that new songs load and radio continues indefinitely.  

Great App, thanks for the hard work you put into it!

**Comment by 3onyc** [comment]
This same issue exists with the daily mixes, I'm not sure whether this is a limitation of the library, or something that just needs to be implemented though.

**Comment by Fornoth** [comment]
This is most likely because Spotify sends over just a set of songs, and not the actual radio station. Nothing I can fix unfortunately
