### ISSUE TITLE
[Feature Request] Play Spotify Playlist from console arg

### ISSUE THREAD

**Issue by tatoosh** [Fornoth/spotify-connect-web#141]
Is it possible to play a spotify track list by a console argument or web curl?
Actually i am using mopidy but its slow on loading because of many playlists in my spotify account i think.

**Comment by Fornoth** [comment]
This isn't something I can provide in spotify-connect-web, but you can do it via the Spotify Web APIs https://developer.spotify.com/web-api/start-a-users-playback/
