### ISSUE TITLE
Segmentation fault on Pi2

### ISSUE THREAD

**Issue by maumi** [Fornoth/spotify-connect-web#19]
Hey,

on my Cubox spoti connect runs fine for weeks. But on both of my 2 Pi's (Pi 2) when I run it without debug (-d) I get a segfault. For now I can use it in debug mode but I'm interested to know where this comes from. Have also tried to run it with unchanged github code (only needs to change card to device in cons_cb.py) because of pyalsa > 0.8
I think the fault only triggers when accessing webpage.

**Comment by LeanderK** [comment]
thats really weird o.O. Do you have the error?

**Comment by Fornoth** [comment]
Try commenting out https://github.com/Fornoth/spotify-connect-web/blob/master/connect.py#L87
If that doesn't help, can you paste the error here?

**Comment by maumi** [comment]
commenting out zeroconf_vars help. Thanks
