### ISSUE TITLE
No Event if playback queue ends

### ISSUE THREAD

**Issue by maumi** [Fornoth/spotify-connect-web#20]
If you play only a single song or reach the end of your queue, no event will be triggered.
That's why the audio device isn't released with the pull request from @JozoVilcek and I use the events to power off some things.
I think it hangs because it's waiting for new data, but there is no. In log you will get a "buffer underrun" warning for this.

**Comment by Fornoth** [comment]
I can't seem to duplicate this, but there's an event named `SpPlaybackNotifyAudioDeliveryDone` in the newer versions. I'll add support for that after I add support for the newer libraries

**Comment by Fornoth** [comment]
I pushed support for the newer libraries (copies are on issue #25), try those and see if it releases the device

**Comment by maumi** [comment]
hey, tried with newer libraries and it works. Thanks man.
