### ISSUE TITLE
Odroid C1+

### ISSUE THREAD

**Issue by tokazio** [Fornoth/spotify-connect-web#21]
Trying to launch with:

``` bash
sudo LD_LIBRARY_PATH=$PWD python main.py -d
```

Gives me:

``` bash
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from connect import Connect
  File "/spotify-connect-web/connect.py", line 8, in <module>
    from console_callbacks import audio_arg_parser, mixer, error_callback, connection_callbacks, debug_callbacks, playback_callbacks, playback_setup
  File "/spotify-connect-web/console_callbacks.py", line 16, in <module>
    audio_arg_parser.add_argument('--mixer', '-m', help='alsa mixer name for volume control', default=alsa.mixers()[0])
IndexError: list index out of range
```

My audio configuration is:

``` bash
cat /proc/asound/cards
 0 [ODROIDHDMI     ]: SOC-Audio - ODROID-HDMI
                      ODROID-HDMI
 1 [UD501          ]: USB-Audio - TEAC UD-501
                      TEAC Corporation TEAC UD-501 at usb-lm0-1, high speed
 2 [Set            ]: USB-Audio - C-Media USB Headphone Set
                      C-Media USB Headphone Set at usb-lm1-1.1, full speed
```

or with python

``` python
import alsaaudio
alsaaudio.cards()
```

return

``` python
[u'ODROIDHDMI', u'UD501', u'Set']
```

I precise that i don't know python.

**Comment by maumi** [comment]
what do you get when typing "amixer" in bash?

**Comment by tokazio** [comment]
nothing

**Comment by maumi** [comment]
that explains the error. 2 choices: use a softvol mixer, see issue #11 
2. choice: comment any line out using mixer in code in connect.py and console_callbacks.py, but then you can't change the volume.

**Comment by tokazio** [comment]
Ok it's working.
I have the same problem that i have with 'scplayer' the sound is stuttering on my TEAC UD501 DAC (OTG). [here](https://github.com/crsmoro/scplayer/issues/15)

Do you think that it's a spotify embbed lib problem?

Because it's working fine with [this DAC](CM108AH DAC)

``` bash
Requesting Bytes: 2863k => 2995k +132k (used: 268k, buf: 576k, thres: 272k, rate: 320k)
Requesting Bytes: 2995k => 3127k +132k (used: 284k, buf: 608k, thres: 288k, rate: 320k)
Requesting Bytes: 3127k => 3273k +146k (used: 285k, buf: 640k, thres: 304k, rate: 320k)
Requesting Bytes: 3273k => 3413k +140k (used: 308k, buf: 672k, thres: 320k, rate: 320k)
Requesting Bytes: 3413k => 3541k +128k (used: 336k, buf: 704k, thres: 336k, rate: 320k)
Requesting Bytes: 3541k => 3681k +140k (used: 340k, buf: 736k, thres: 352k, rate: 320k)
Requesting Bytes: 3681k => 3821k +140k (used: 356k, buf: 768k, thres: 368k, rate: 320k)
Requesting Bytes: 3821k => 3953k +132k (used: 380k, buf: 800k, thres: 384k, rate: 320k)
Requesting Bytes: 3953k => 4085k +132k (used: 396k, buf: 832k, thres: 400k, rate: 320k)
Requesting Bytes: 4085k => 4215k +130k (used: 413k, buf: 838k, thres: 416k, rate: 320k)
```

**Comment by maumi** [comment]
My output looks similar. Haven't had any stuttering ever. But I have no Odroid to test. Have used it on a pi 2 (internal chinch, internal HDMI, external cheap usb sound) with OSMC and also on a Cubox i2 with debian. For both devices I use the armhf lib. 
I have no real idea what kind of problem it is. But because it's also a problem in scplayer I think it should be a lib problem or sound card compatibility problem. 
Do you use the DAC otherwise with alsa?

**Comment by tokazio** [comment]
Ok i've found! it's an os problem or os configuration problem.
Tried with another image and sounds good with scplayer and openal.
Great work guys! thanks.

scplayer/spotify-connect-web and the lib works fine.
