### ISSUE TITLE
Remote control the this from program

### ISSUE THREAD

**Issue by wendelit** [Fornoth/spotify-connect-web#32]
Hallo, 
I would like to be able to start and play Spotify songs on this with a program. Is that possibale?

**Comment by SSintermann** [comment]
Well,

as you need a spotify account you can control it via your "other" Spotify device... at least that's what I do.

**Comment by maumi** [comment]
Or you can start with http. Yourip:4000 and then play. You also can use http requests to call it with any device

**Comment by Cesc1986** [comment]
Hi maumi, I have a similar question. Can you please elaborate on how to use http requests? 

Spotify Connect works so far for and yes, I can start and control it with my iPad, Mac or whatever device in the same LAN. However the idea is to start it headless on my Raspberry, with me controlling just the start of a playlist via an button/script on my apache server. Only when I decide to change the music, I will start my spotify app on my iPad and then control the music on my raspberry via spotify connect.

**Comment by maumi** [comment]
afaik you can only use the basic calls via http request. so play/pause, prev/next.
you can use curl or wget on pi with the adress 
YOURIP:4000/api/playback/play 
other commands are pause, prev, next.
If you can use vol up and down I'm not sure at the moment.
If you call play your playlist will start where it last stops.

**Comment by Cesc1986** [comment]
I understand ... however that's not exactly what I am looking for. I want to give the command to start a certain song or playlist. Do you think implement such a functionality is possible without too much hassle?

**Comment by Fornoth** [comment]
Until librespot is ready, this program can only control itself, and you can't tell it to play a song/playlist/etc without using an external program (something like the spotify client)

You would have to use something like this https://github.com/badfortrains/spotcontrol

**Comment by Fornoth** [comment]
I'm gonna close this for now, feel free to re-open if you're still having problems

**Comment by axelsimon** [comment]
Just a quick question, how hard would it be to write a Kodi add-on that would use the API to display what's now playing and offer the basics of playback control? (play, pause, previous and nex, possibly toggling repeat and shuffle)
With my limited knowledge, it looks like the right calls to the API from the Kodi add-on would do just that, without the need for something spotcontrol or librespot, no?

**Comment by Fornoth** [comment]
@axelsimon yeah, it should be possible, @noemu posted a Kodi plugin that they started in #70 https://github.com/noemu/script.example-master
