### ISSUE TITLE
DisplayName not stored after reboot

### ISSUE THREAD

**Issue by matzex** [Fornoth/spotify-connect-web#36]
On my raspberry pi 2 the display name which you can set in the web gui is used in all clients and this works good. But after one reboot of my raspberry pi the name is not set again and all clients are using "TestConnect" as the name.
The chosen name should be used also after a reboot.

**Comment by gusse** [comment]
use --name to launch it with the name you want it to have.

**Comment by matzex** [comment]
okay, thanks.
