### ISSUE TITLE
Normalization of volume between songs

### ISSUE THREAD

**Issue by ghost** [Fornoth/spotify-connect-web#51]
Is it possible to have normalization between songs?

**Comment by Fornoth** [comment]
I feel like this is out of scope for this project, but you can try using the LADSPA alsa plugin
https://bbs.archlinux.org/viewtopic.php?id=99185

**Comment by Noroji** [comment]
And what about the "built-in" normalization of Spotify? Is it somehow possible to activate this feature?

**Comment by Fornoth** [comment]
@Noroji the library that were using doesn't have that feature built in :(

**Comment by Fornoth** [comment]
I'm gonna close this for now, feel free to re-open if you're still having problems
