### ISSUE TITLE
Segmentation fault on running spotify-connect-web

### ISSUE THREAD

**Issue by TimHausmann** [Fornoth/spotify-connect-web#59]
HI, I hope this is the right place for a problem like this. I tried the installation following the intructions but I get a Segmantation fault message when trying to execute `./spotify-connect-web`

maybe I can give a little more information: I am using a raspberry pi wih volumio 1.55

**Comment by Fornoth** [comment]
I'm guessing you figured out your problem?

**Comment by TimHausmann** [comment]
Yeah, I guess it's because I use a Raspberry Pi 1, right? Got it working for me using the latest console_callbacks.py with the web-chroot build. I'm quite a noob to this. Would love to learn more, but don't want to bother you ;)

**Comment by Fornoth** [comment]
Yeah, unfortunately the PyInstaller version isn't available for Rpi 1 for the time being. And feel free to ask me whatever about this!
I'm also in https://gitter.im/sashahilton00/spotify-connect-resources
