### ISSUE TITLE
Adding a License

### ISSUE THREAD

**Issue by Fornoth** [Fornoth/spotify-connect-web#63]
I plan on adding the MIT license, given that all contributors agree (Just comment on this issue whether you agree or not)
@djmaze
@chukysoria
@plietar
@diogocp
@sashahilton00
@Alex131089
@JozoVilcek

**Comment by diogocp** [comment]
:+1:

**Comment by plietar** [comment]
👍

**Comment by djmaze** [comment]
:+1:

**Comment by JozoVilcek** [comment]
👍

**Comment by sashahilton00** [comment]
Agreed

**Comment by chukysoria** [comment]
👌

**Comment by u1735067** [comment]
Yep fine
