### ISSUE TITLE
Can you add the --cors option?

### ISSUE THREAD

**Issue by CatoAntonsen** [Fornoth/spotify-connect-web#69]
I try to use the --cors argument that main.py offers, but it doesn't seem that spotify-connect-web (Pyinstaller Test Release 0.0.3) has implemented it...?

```
# ./spotify-connect-web -n MAGICMIRROR -o plughw:CARD=ALSA,DEV=1 --cors http://raspberrypi:8080

Loading Spotify library...
min_volume_range: 0.0
usage: spotify-connect-web [-h]
                           [--device DEVICE | --playback_device PLAYBACK_DEVICE]
                           [--mixer_device_index MIXER_DEVICE_INDEX]
                           [--mixer MIXER] [--dbrange DBRANGE] [--debug]
                           [--key KEY] [--username USERNAME]
                           [--password PASSWORD] [--name NAME]
                           [--bitrate {90,160,320}]
                           [--credentials CREDENTIALS]
spotify-connect-web: error: unrecognized arguments: --cors http://raspberrypi:8080
```

Anyway, thanks for a GREAT and easy way of making my RPi a Spotify Connect'ed device! :-)

**Comment by exetico** [comment]
Nope :-( That's SAD. Damn..
![image](https://cloud.githubusercontent.com/assets/3549445/17903515/10010004-696c-11e6-9f94-76f8961f062a.png)

**Comment by Fornoth** [comment]
Even though it doesn't show it in `--help`, the option should still work (at least for 0.0.3)
Try doing `grep -i cors main.py` in the main directory

**Comment by exetico** [comment]
Well Fornoth - As you can see, the option isn't supported. But, maybe we have to use it, in another way.

**Comment by Fornoth** [comment]
@exetico can you double check that you're running the 0.0.3 release by checking if main.py has any CORS references?

**Comment by exetico** [comment]
I can see that "CORS" is in the top header as "import CORS".
I'm using the Alpha-build of 0.0.3 currently. So.. Maybe that why?
https://github.com/Fornoth/spotify-connect-web/releases/download/0.0.3-alpha/spotify-connect-web_0.0.3-alpha.tar.gz

**Comment by Fornoth** [comment]
@exetico can you try re-downloading the 0.0.3 release? I've tried it on two devices, and the --cors argument exists

**Comment by Fornoth** [comment]
I'm gonna close this for now, feel free to re-open if you're still having problems
