### ISSUE TITLE
remotecontrol: get Song Information

### ISSUE THREAD

**Issue by noemu** [Fornoth/spotify-connect-web#70]
Hello,

i try to make an remote control addon for kodi/rpi2.

Is there an easy way to get the Song-Information/Albumcover.

Because "requests" doesn't support javascript and so i can't get the Infromation from the webinterface.

( play, pause... should work with "YOURIP:4000/api/playback/play " (#32))

edit.: i found sth. at "/api/info/metadata" with the "Pyinstaller Test Release 0.0.3"

**Comment by danifr** [comment]
HI @noemu, I'm very interested on this one. Please keep us posted about any progress you make :)
Is there anywhere we can follow this development? Thanks!

**Comment by noemu** [comment]
try: https://github.com/noemu/script.example-master ;)
