### ISSUE TITLE
webserver shuffle/repeat: Internal Server Error

### ISSUE THREAD

**Issue by noemu** [Fornoth/spotify-connect-web#75]
Hi,
I'm using the spotify-connect-web_0.0.3-alpha RPI Release.

The Webserver Shuffle and Repeat function doesn't work.

GET ip:4000/api/playback/shuffle  gives an "500 (INTERNAL SERVER ERROR)"
same with repeat.

Everything Else (play/pause/prev/next) and (/api/info/metadata, /api/info/status) works perfectly.

**Comment by Fornoth** [comment]
This is fixed in the source (7b1c426), but I haven't made a release with it yet

**Comment by Alootje** [comment]
Hello Fornoth,

Is there an ETA when you think this will be released?

**Comment by ghost** [comment]
@Alootje https://github.com/Fornoth/spotify-connect-web has build instructions if you want to experiment yourself.

**Comment by Fornoth** [comment]
A new build with the fix has been released 
https://github.com/Fornoth/spotify-connect-web/releases/tag/0.0.4-alpha
