### ISSUE TITLE
Segmentation Fault on RPI

### ISSUE THREAD

**Issue by l3d00m** [Fornoth/spotify-connect-web#79]
If I try to run this util, I get a ´segmentation fault´. I'm using the newest 0.3 version on a Raspberry Pi 1. 

I've put my appkey in place, and commented the line with zeroconf_var in connect.py.

Thanks for your help!

**Comment by Geophagus** [comment]
Hey,

I had the same problem but used this: https://github.com/JozoVilcek/spotify-connect-web and it seems to work.

**Comment by Fornoth** [comment]
The packaged release isn't compatible with RPi 1 for now, you'll have to install spotify-connect-web from source

**Comment by flori4n** [comment]
I did have this issue with another git project. 
Try to create a swap file [http://www.cyberciti.biz/faq/linux-add-a-swap-file-howto/](swap-file-howto) and let us know

**Comment by Fornoth** [comment]
Also, you have the option of installing from chroot now since I updated it to be on par with the chroot

**Comment by h0lger** [comment]
Is it possible to compile for RPi 1? I would like to use the playback_device you have implemented. The source only have the device option.

**Comment by Fornoth** [comment]
@h0lger use the chroot option, it works with RPi 1, and should have the same features as the packaged release

**Comment by l3d00m** [comment]
Thanks for your help!

You may close this now.

**Comment by NewBe001** [comment]
**@Fornoth** I have tried the chroot option on my RPi 1 with LibreElec but I get stuck on the install. I keep getting: curl: (23) Failed writing body (0 != 16384)
Any good tip on how to resolve this?

Thanks in advance.

**Comment by l3d00m** [comment]
Maybe this could help you @NewBe001 ?  
http://stackoverflow.com/questions/36879168/error-installing-composer-curl-23-failed-writing-body-0-16133
