### ISSUE TITLE
Possibility to set 96kHz, 24 bit

### ISSUE THREAD

**Issue by cadavre** [Fornoth/spotify-connect-web#81]
Is it possible to set 96kHz rate and 24bit playback?

I used `pcm.setformat(alsa.PCM_FORMAT_S24_LE)` and it's fine, but when I set `RATE=96000` my playback is 4x faster than it should.

If answer to my question is no as simple as I think it could be I have another question: what can I do to make use of 24bit/96kHz DAC?

**Comment by Fornoth** [comment]
I'm not sure if it's possible to change the audio quality using the current spotify library (there is the `--bitrate` option, but I'm not sure if it does anything)

**Comment by Fornoth** [comment]
I'm gonna close this for now, feel free to re-open if you're still having problems
