### ISSUE TITLE
Just a heads up

### ISSUE THREAD

**Issue by avesst** [Fornoth/spotify-connect-web#90]
This is not really an issue with the software and you can close this issue right away. Just wanted to point out that the README.md lists the URL for 0.0.2-alpha under "Quickstart using a packaged release" while the URL points to 0.0.3-alpha under "Quickstart using a pre-built chroot".

**Comment by Fornoth** [comment]
Thanks! I've gone ahead and updated it

**Comment by avesst** [comment]
Nice. Thank you for your work with this, exactly what I need :)
