### ISSUE TITLE
LibrELEC add-on configuration

### ISSUE THREAD

**Issue by tovabbi** [Fornoth/spotify-connect-web#92]
So I got the spotify_appkey.key and copied it to /storage/.kodi/addons/service.spotify-connect-web. Then what? I guess it is this fork: https://github.com/awiouy/spotify-connect-web @awiouy

**Comment by awiouy** [comment]
Hello tovabbi,

spotifiy-connect-web is provided as an addon to LibreELEC.
Support for the addon is provided via a dedicated LibreELEC forum thread (https://forum.libreelec.tv/thread-1206.html).

To reply to you question: select LibreELEC as the playback device from a Spotify app, eg on android or ios

**Comment by tovabbi** [comment]
Ok, thanks, it would be nice to add the support forum url to the readme, since I wasn't able to google it.
